### ISSUE TITLE
Traceback (most recent call last):   File ".\render_360.py", line 30, in <module>     from scene import Scene, GaussianModel, GaussianModelSQ, GaussianModelVQ ImportError: cannot import name 'GaussianModelVQ' from 'scene' (D:\code\3dgs\efficientgaussian\scene\__init__.py)

### ISSUE THREAD

**Issue by Konsla99** [Sharath-girish/efficientgaussian#9]
Traceback (most recent call last):
  File ".\render_360.py", line 30, in <module>
    from scene import Scene, GaussianModel, GaussianModelSQ, GaussianModelVQ
ImportError: cannot import name 'GaussianModelVQ' from 'scene' (D:\code\3dgs\efficientgaussian\scene\__init__.py)

can not use render_360.py

**Comment by Konsla99** [comment]
vq모델이 미완성이라 해당 부분을 주석처리하고 사용하면 해결됩니다.
